# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_template.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 667)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(900, 10, 211, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../OneDrive/Desktop/resizedalbertaloop.png"))
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(820, 90, 111, 31))
        self.label2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(780, 160, 191, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.controlsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.controlsLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.controlsLayout.setContentsMargins(0, 0, 0, 0)
        self.controlsLayout.setObjectName("controlsLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.controlsLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.controlsLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.controlsLayout.addWidget(self.pushButton_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 460, 111, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(50, 490, 191, 81))
        self.status_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setWordWrap(False)
        self.status_label.setObjectName("status_label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 140, 291, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(22)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.battery_volt_lcd = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.battery_volt_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.battery_volt_lcd.setObjectName("battery_volt_lcd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.battery_volt_lcd)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.pressure_vessel_lcd = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.pressure_vessel_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pressure_vessel_lcd.setObjectName("pressure_vessel_lcd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pressure_vessel_lcd)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.brake_tank_pressure_lcd = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.brake_tank_pressure_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.brake_tank_pressure_lcd.setObjectName("brake_tank_pressure_lcd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.brake_tank_pressure_lcd)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.pod_temp_lcd = QtWidgets.QLCDNumber(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pod_temp_lcd.sizePolicy().hasHeightForWidth())
        self.pod_temp_lcd.setSizePolicy(sizePolicy)
        self.pod_temp_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pod_temp_lcd.setObjectName("pod_temp_lcd")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pod_temp_lcd)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.battery_temp_lcd = QtWidgets.QLCDNumber(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.battery_temp_lcd.sizePolicy().hasHeightForWidth())
        self.battery_temp_lcd.setSizePolicy(sizePolicy)
        self.battery_temp_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.battery_temp_lcd.setObjectName("battery_temp_lcd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.battery_temp_lcd)
        self.motor_temp_lcd = QtWidgets.QLCDNumber(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motor_temp_lcd.sizePolicy().hasHeightForWidth())
        self.motor_temp_lcd.setSizePolicy(sizePolicy)
        self.motor_temp_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.motor_temp_lcd.setObjectName("motor_temp_lcd")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.motor_temp_lcd)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 590, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 90, 71, 16))
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(380, 50, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AlbertaLoop Command Centre"))
        self.label2.setText(_translate("MainWindow", "Controls"))
        self.pushButton.setText(_translate("MainWindow", "Change Pod State"))
        self.pushButton_2.setText(_translate("MainWindow", "Restart TCP Connection"))
        self.pushButton_3.setText(_translate("MainWindow", "Display Packet Logger"))
        self.label_2.setText(_translate("MainWindow", "Pod State"))
        self.label_3.setText(_translate("MainWindow", "Battery Temperature     "))
        self.label_4.setText(_translate("MainWindow", "Battery Voltage"))
        self.label_7.setText(_translate("MainWindow", "Pressure Vessel Pressure"))
        self.label_8.setText(_translate("MainWindow", "Brake Air Tank Pressure"))
        self.label_9.setText(_translate("MainWindow", "Pod Temperature"))
        self.label_10.setText(_translate("MainWindow", "Motor Temperature"))
        self.label_5.setText(_translate("MainWindow", "Connection with Pod: "))
        self.label_6.setText(_translate("MainWindow", "Pod Status"))
'''
app = QApplication(sys.argv)
window = QMainWindow()

ui = Ui_MainWindow()
ui.setupUi(window)

window.show()
sys.exit(app.exec_())
'''
