from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 798)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(20, -10, 1121, 731))
        self.main_frame.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.estop_button = QtWidgets.QPushButton(self.main_frame)
        self.estop_button.setGeometry(QtCore.QRect(20, 40, 151, 51))
        self.estop_button.setStyleSheet("background-color: rgb(170, 0, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 63 8pt \"Segoe UI Semibold\";")
        self.estop_button.setObjectName("estop_button")
        self.left_frame = QtWidgets.QFrame(self.main_frame)
        self.left_frame.setGeometry(QtCore.QRect(20, 100, 311, 581))
        self.left_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.left_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.speed_guage_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.speed_guage_layout.setContentsMargins(0, 0, 0, 0)
        self.speed_guage_layout.setObjectName("speed_guage_layout")
        self.time_elapsed_label = QtWidgets.QLabel(self.left_frame)
        self.time_elapsed_label.setGeometry(QtCore.QRect(80, 400, 171, 41))
        self.time_elapsed_label.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";\n"
        "color: rgb(255, 255, 255);")
        self.time_elapsed_label.setObjectName("time_elapsed_label")
        self.estimated_progress_title_label = QtWidgets.QLabel(self.left_frame)
        self.estimated_progress_title_label.setGeometry(QtCore.QRect(80, 450, 161, 21))
        self.estimated_progress_title_label.setStyleSheet("font: 75 10pt \"Microsoft YaHei UI\";\n"
        "color: rgb(255, 255, 255);")
        self.estimated_progress_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.estimated_progress_title_label.setObjectName("estimated_progress_title_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.left_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 480, 241, 59))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.progress_bar_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.progress_bar_layout.setContentsMargins(0, 0, 0, 0)
        self.progress_bar_layout.setObjectName("progress_bar_layout")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressBar.setMaximum(500)
        self.progressBar.setProperty("value", 115)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.progress_bar_layout.addWidget(self.progressBar)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.left_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 310, 141, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.position_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.position_layout.setContentsMargins(0, 0, 0, 0)
        self.position_layout.setObjectName("position_layout")
        self.position_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_label.sizePolicy().hasHeightForWidth())
        self.position_label.setSizePolicy(sizePolicy)
        self.position_label.setStyleSheet("font: 75 9pt \"Microsoft YaHei\";\n"
        "color: rgb(218, 218, 218);")
        self.position_label.setObjectName("position_label")
        self.position_layout.addWidget(self.position_label)
        self.position_ind = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.position_ind.setStyleSheet("font: 75 14pt \"Microsoft YaHei\";\n"
        "color: rgb(255, 255, 255);")
        self.position_ind.setAlignment(QtCore.Qt.AlignCenter)
        self.position_ind.setObjectName("position_ind")
        self.position_layout.addWidget(self.position_ind)
        self.DataFrame = QtWidgets.QFrame(self.main_frame)
        self.DataFrame.setGeometry(QtCore.QRect(600, 100, 501, 581))
        self.DataFrame.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.DataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataFrame.setObjectName("DataFrame")

        self.healthChkTable = QtWidgets.QTableView(self.DataFrame)
        self.healthChkTable.setGeometry(QtCore.QRect(250, 0, 251, 291))
        self.healthChkTable.setObjectName("healthChkTable")


        self.gridLayoutWidget = QtWidgets.QWidget(self.DataFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 300, 241, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Voltage_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Voltage_Label.setObjectName("Voltage_Label")
        self.gridLayout.addWidget(self.Voltage_Label, 1, 0, 1, 1)
        self.Current_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Current_label.setObjectName("Current_label")
        self.gridLayout.addWidget(self.Current_label, 2, 0, 1, 1)
        self.Cell_4_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Cell_4_label.setObjectName("Cell_4_label")
        self.gridLayout.addWidget(self.Cell_4_label, 0, 4, 1, 1)
        self.Cell_2_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Cell_2_label.setObjectName("Cell_2_label")
        self.gridLayout.addWidget(self.Cell_2_label, 0, 2, 1, 1)
        self.Temperature_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Temperature_label.setObjectName("Temperature_label")
        self.gridLayout.addWidget(self.Temperature_label, 3, 0, 1, 1)
        self.Cell_1_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Cell_1_label.setObjectName("Cell_1_label")
        self.gridLayout.addWidget(self.Cell_1_label, 0, 1, 1, 1)
        self.Cell_3_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Cell_3_label.setObjectName("Cell_3_label")
        self.gridLayout.addWidget(self.Cell_3_label, 0, 3, 1, 1)
        self.Cell_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Cell_label.setObjectName("Cell_label")
        self.gridLayout.addWidget(self.Cell_label, 0, 0, 1, 1)


        self.telemetryTable = QtWidgets.QTableWidget(self.DataFrame)
        self.telemetryTable.setGeometry(QtCore.QRect(0, 0, 251, 581))
        self.telemetryTable.setObjectName("telemetryTable")
        self.telemetryTable.setColumnCount(1)
        self.telemetryTable.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.telemetryTable.setHorizontalHeaderItem(0, item)
        self.label = QtWidgets.QLabel(self.main_frame)
        self.label.setGeometry(QtCore.QRect(700, 40, 81, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.simulation_button = QtWidgets.QPushButton(self.main_frame)
        self.simulation_button.setGeometry(QtCore.QRect(190, 40, 151, 51))
        self.simulation_button.setStyleSheet("background-color: rgb(240, 165, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 63 8pt \"Segoe UI Semibold\";")
        self.simulation_button.setObjectName("simulation_button")
        self.StateFrame = QtWidgets.QFrame(self.main_frame)
        self.StateFrame.setGeometry(QtCore.QRect(350, 100, 241, 581))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.StateFrame.setFont(font)
        self.StateFrame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.StateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StateFrame.setObjectName("StateFrame")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.StateFrame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(50, 480, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.current_state_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.current_state_layout.setContentsMargins(0, 0, 0, 1)
        self.current_state_layout.setSpacing(6)
        self.current_state_layout.setObjectName("current_state_layout")
        self.current_state_title = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_state_title.sizePolicy().hasHeightForWidth())
        self.current_state_title.setSizePolicy(sizePolicy)
        self.current_state_title.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";\n"
        "color: rgb(255, 255, 255);")
        self.current_state_title.setObjectName("current_state_title")
        self.current_state_layout.addWidget(self.current_state_title)
        self.current_state_ind = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_state_ind.sizePolicy().hasHeightForWidth())
        self.current_state_ind.setSizePolicy(sizePolicy)
        self.current_state_ind.setStyleSheet("color: rgb(255, 255, 255);\n"
        "background-color: rgb(255, 85, 0);\n"
        "font: 75 8pt \"Microsoft YaHei\";")
        self.current_state_ind.setAlignment(QtCore.Qt.AlignCenter)
        self.current_state_ind.setObjectName("current_state_ind")
        self.current_state_layout.addWidget(self.current_state_ind)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.StateFrame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(50, 10, 168, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.telemetry_connection_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.telemetry_connection_layout.setContentsMargins(0, 0, 0, 1)
        self.telemetry_connection_layout.setSpacing(6)
        self.telemetry_connection_layout.setObjectName("telemetry_connection_layout")
        self.current_state_title_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_state_title_2.sizePolicy().hasHeightForWidth())
        self.current_state_title_2.setSizePolicy(sizePolicy)
        self.current_state_title_2.setStyleSheet("font: 75 10pt \"Microsoft YaHei\";\n"
        "color: rgb(255, 255, 255);")
        self.current_state_title_2.setObjectName("current_state_title_2")
        self.telemetry_connection_layout.addWidget(self.current_state_title_2)
        self.current_state_ind_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_state_ind_2.sizePolicy().hasHeightForWidth())
        self.current_state_ind_2.setSizePolicy(sizePolicy)
        self.current_state_ind_2.setStyleSheet("color: rgb(255, 255, 255);\n"
        "font: 75 8pt \"Microsoft YaHei\";")
        self.current_state_ind_2.setAlignment(QtCore.Qt.AlignCenter)
        self.current_state_ind_2.setObjectName("current_state_ind_2")
        self.telemetry_connection_layout.addWidget(self.current_state_ind_2)
        self.simulation_button_2 = QtWidgets.QPushButton(self.main_frame)
        self.simulation_button_2.setGeometry(QtCore.QRect(360, 40, 151, 51))
        self.simulation_button_2.setStyleSheet("background-color: rgb(240, 165, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 63 8pt \"Segoe UI Semibold\";")
        self.simulation_button_2.setObjectName("simulation_button_2")
        self.simulation_button_3 = QtWidgets.QPushButton(self.main_frame)
        self.simulation_button_3.setGeometry(QtCore.QRect(530, 40, 151, 51))
        self.simulation_button_3.setStyleSheet("background-color: rgb(240, 165, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 63 8pt \"Segoe UI Semibold\";")
        self.simulation_button_3.setObjectName("simulation_button_3")
        self.simulation_button_4 = QtWidgets.QPushButton(self.main_frame)
        self.simulation_button_4.setGeometry(QtCore.QRect(700, 40, 151, 51))
        self.simulation_button_4.setStyleSheet("background-color: rgb(240, 165, 0);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 63 8pt \"Segoe UI Semibold\";")
        self.simulation_button_4.setObjectName("simulation_button_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.estop_button.setText(_translate("MainWindow", "EMERGENCY STOP"))
        self.time_elapsed_label.setText(_translate("MainWindow", "Time Elapsed: 0:26:35"))
        self.estimated_progress_title_label.setText(_translate("MainWindow", "Estimated Progress"))
        self.progressBar.setFormat(_translate("MainWindow", "%v / 400 m"))
        self.position_label.setText(_translate("MainWindow", "Position: "))
        self.position_ind.setText(_translate("MainWindow", "115 m"))
        self.Voltage_Label.setText(_translate("MainWindow", "Voltage"))
        self.Current_label.setText(_translate("MainWindow", "Cuurent"))
        self.Cell_4_label.setText(_translate("MainWindow", "4"))
        self.Cell_2_label.setText(_translate("MainWindow", "2"))
        self.Temperature_label.setText(_translate("MainWindow", "Temperature"))
        self.Cell_1_label.setText(_translate("MainWindow", "1"))
        self.Cell_3_label.setText(_translate("MainWindow", "3"))
        self.Cell_label.setText(_translate("MainWindow", "Cell"))
        item = self.telemetryTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Team ID"))
        item = self.telemetryTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.telemetryTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Acceleration"))
        item = self.telemetryTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Velocity"))
        item = self.telemetryTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Position"))
        item = self.telemetryTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Pod Temperture"))
        item = self.telemetryTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Battery 1 Current"))
        item = self.telemetryTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Battery1 Current"))
        item = self.telemetryTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Battery2 Current"))
        item = self.telemetryTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Battery4 Current"))
        item = self.telemetryTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Battery1 Voltage"))
        item = self.telemetryTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Battery2 Voltage"))
        item = self.telemetryTable.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Battery3 Voltage"))
        item = self.telemetryTable.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Battery4 Voltage"))
        item = self.telemetryTable.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Battery1 Temperature"))
        item = self.telemetryTable.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "Battery2 Temperature"))
        item = self.telemetryTable.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "Battery3 Temperature"))
        item = self.telemetryTable.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Battery4 Temperature"))
        self.simulation_button.setText(_translate("MainWindow", "ENTER SIMULATION"))
        self.current_state_title.setText(_translate("MainWindow", "Current State"))
        self.current_state_ind.setText(_translate("MainWindow", "Acceleration"))
        self.current_state_title_2.setText(_translate("MainWindow", "Telemetry Connection"))
        self.current_state_ind_2.setText(_translate("MainWindow", "No Connection"))
        self.simulation_button_2.setText(_translate("MainWindow", "ENTER SIMULATION"))
        self.simulation_button_3.setText(_translate("MainWindow", "ENTER SIMULATION"))
        self.simulation_button_4.setText(_translate("MainWindow", "ENTER SIMULATION"))
        
    def updateTelemetry(self, data):
        model = TableModel(data)
        self.healthChkTable.setModel(model)

class TableModel(QtCore.QAbstractTableModel):
        def __init__(self, data):
                super(TableModel, self).__init__()
                self._data = data

        def rowCount(self, index):
                return len(self._data)

        def columnCount(self, index):
                return len(self._data[0])

        def data(self, index, role):
                if role == Qt.DisplayRole:
                        return self._data[index.row()][index.column()]


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
