[package]
name = "bamocar"
version = "0.1.0"
edition = "2018"
default-run = "server"

[dependencies]
env_logger = "0.9.0"
home = "0.5.3"
log = "0.4.14"
nix = "0.23.0"
rand = "0.8.4"
serialport = "4.0.1"
